"""Centralized UI text strings.

The current UI displays English labels by default.  Validation messages stay
Chinese because they are intended to be explicit for the current operator.
Later language packs can replace this module with keyed dictionaries.
"""

APP_TITLE = "JP Equity Backtest Console"
APP_SUBTITLE = "J-Quants historical backtest launcher using direct linear factor weighting"

GROUP_DATES = "Backtest Date Range"
GROUP_POOL = "Universe Filters"
GROUP_FACTORS = "Factor Composite"
GROUP_RUN = "Run Backtest"

START_DATE = "Start date"
END_DATE = "End date"
EFFECTIVE_RANGE = "Effective range"
FREQUENCY = "Frequency"
MONTHLY = "Monthly"
WEEKLY = "Weekly"

MARKET_CAP_MODE = "Market-cap filter"
ENABLE_MARKET_CAP = "Enable market-cap filter"
RANK_MIN = "Rank min"
RANK_MAX = "Rank max"
MIN_MARKET_CAP = "Min market cap (bn JPY)"
MAX_MARKET_CAP = "Max market cap (bn JPY)"
ENABLE_LIQUIDITY = "Enable liquidity filter"
LIQUIDITY_LOOKBACK = "Liquidity lookback days"
MIN_VOLUME = "Min avg daily volume"
ENABLE_VOLATILITY = "Enable volatility filter"
VOL_LOOKBACK = "Volatility lookback days"
MAX_VOL = "Max annualized volatility"
SELECTION_TOP_N = "Pool top N"
SELECTION_SORT = "Selection sort"
ENABLE_MAX_LOT_COST = "Enable max lot cost"
MAX_LOT_COST = "Max lot cost (JPY)"
ENABLE_SECTOR_CONSTRAINTS = "Enable sector constraints"
MAX_NAMES_PER_SECTOR = "Max names per sector"
SECTOR_CAP_MODE = "Sector cap mode"

FACTOR = "Factor"
ENABLED = "Enabled"
WEIGHT = "Weight"
DESCRIPTION = "Description"
RESTORE_DEFAULTS = "Restore defaults"
FORMULA = "Composite formula"

INITIAL_CAPITAL = "Initial capital"
TARGET_COUNT = "Target count"
GROSS_EXPOSURE = "Max gross exposure"
SHORT_HEDGE_NOTE = "Optional research-mode short hedge. Use this to add a light bottom-ranked short leg for beta reduction."
ENABLE_SHORT_HEDGE = "Enable short hedge"
SHORT_GROSS_EXPOSURE = "Short gross exposure"
SHORT_TARGET_COUNT = "Short target count"
SHORT_CONSTRUCTION_MODE = "Short construction mode"
SHORT_WEIGHTING_MODE = "Short weighting mode"
SHORT_EXPANSION_MODE = "Short expansion mode"
SHORT_ADV_THRESHOLD = "Short ADV60 threshold"
SHORT_SECTOR_CAP = "Short sector cap"
SHORT_MIN_NAMES = "Short min names"
SHORT_MAX_SINGLE_WEIGHT = "Short max single weight"
TRANSACTION_COST = "Transaction cost (bps)"
SLIPPAGE = "Slippage (bps)"
LOT_SIZE = "Lot size"
ROUND_LOTS = "Round lots"
USE_RISK_GATING = "Use risk gating"
INCLUDE_SP500 = "Include S&P 500 benchmark"
API_KEY = "J-Quants API key"
FORCE_REBUILD = "Force rebuild cache"

START_BACKTEST = "Start Backtest"
STOP_BACKTEST = "Stop"
OPEN_RESULTS = "Open Result Folder"
STATUS_READY = "Ready"
STATUS_RUNNING = "Running..."
STATUS_DONE = "Completed"
STATUS_FAILED = "Failed"
STATUS_STOPPED = "Stopped"

LOG_PLACEHOLDER = "Backtest logs will appear here."

TAB_RUN_SETUP_TOOLTIP = "Set the backtest date window, enter J-Quants credentials, and confirm cache/output paths before launching a run."
TAB_POOL_TOOLTIP = "Control the universe filters used before factor ranking and portfolio construction."
TAB_FACTORS_TOOLTIP = "Choose factor modules, tune linear factor weights, and edit the composite scoring formula."
TAB_ADVANCED_TOOLTIP = "Adjust execution assumptions, runtime options, and market risk settings used by the allocation gate."
TAB_LOGS_TOOLTIP = "Monitor command output, progress, saved result paths, and runtime diagnostics."

RUN_SETUP_DETAILS = "Use this tab in order: confirm the date range, enter J-Quants credentials in the GUI, make sure the cache/output paths are correct, then review the long book and optional short hedge settings."
POOL_DETAILS = "Universe filters are applied before factor scoring. Tightening liquidity and volatility constraints reduces noise and improves tradability, while market-cap and selection sort settings shape the candidate set that the model can rank."
FACTORS_DETAILS = "Factor modules produce the raw signals that feed the composite score. Factor blending is controlled directly by the formula and weights you enter on the Factors tab."
ADVANCED_DETAILS = "Execution settings define how model weights are translated into trades, costs, and lots. The market risk overlay then feeds the allocation gate so exposure can be reduced when stress, realized volatility, and trend confirmation deteriorate."
LOGS_DETAILS = "The log tab is your live run console. Command launch lines, cache events, rebalance progress, summaries, warnings, and failures are colorized so you can quickly spot the important parts during long runs."

MSG_VALIDATION_FAILED = "参数校验失败"
MSG_BACKTEST_DONE = "Backtest completed"
MSG_BACKTEST_FAILED = "Backtest failed"
MSG_NO_RESULT_PATH = "Backtest completed, but no result path was parsed from output."
